# Generated by Django 5.1.3 on 2024-12-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_intr', '0002_country_alter_airport_id_alter_city_id_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='models_name',
        ),
    ]
