# Generated by Django 5.1.3 on 2024-12-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_intr', '0003_remove_airport_models_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='type',
            new_name='flight_class',
        ),
    ]
