# Generated by Django 5.1.3 on 2024-12-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_intr', '0004_rename_type_seat_flight_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
