# Generated by Django 5.1.3 on 2024-12-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_intr', '0005_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='available_services',
        ),
        migrations.AddField(
            model_name='flight',
            name='base_seat_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='business_seat_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_class_seat_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_intr.flight')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_intr.service')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='available_flight_services',
            field=models.ManyToManyField(related_name='offered_on_flights', through='client_intr.ServiceOffer', to='client_intr.service'),
        ),
    ]
