# Generated by Django 5.1.3 on 2024-12-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_intr', '0006_remove_flight_available_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='available_flight_services',
            new_name='available_services',
        ),
    ]
