# Generated by Django 5.1.3 on 2024-12-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_intr', '0007_rename_available_flight_services_flight_available_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
